version: '3'

services:
  translate-bot:
    container_name: translate-bot
    pull_policy: build
    build:
      dockerfile: Dockerfile
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - mariadb

networks:
  mariadb:
    name: MariaDB
    external: true