version: '3'

services:
  translate-bot:
    container_name: translate-bot
    pull_policy: build
    build:
      dockerfile: Dockerfile
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: 10.10.2.39

networks:
  lan:
    name: LAN
    external: true

